from __future__ import annotations

import re
from pathlib import Path

_ROOT_AGENT_RE = re.compile(r"^\s*root_agent\s*=", re.MULTILINE)


class Workspace:
    """Idempotent file access for an ADK project (code-first source of truth)."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)

    def path(self, relative: str) -> Path:
        return self.root / relative

    def write(self, relative: str, content: str) -> bool:
        """Write `content`. Returns True if created/modified, False if unchanged."""
        target = self.path(relative)
        if target.exists() and target.read_text(encoding="utf-8") == content:
            return False
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return True

    def read(self, relative: str) -> str:
        return self.path(relative).read_text(encoding="utf-8")

    def exists(self, relative: str) -> bool:
        return self.path(relative).exists()

    def has_root_agent(self, relative: str = "agent.py") -> bool:
        """Detect the `root_agent = ...` assignment generated by the toolkit (idempotence guard).

        A line-anchored HEURISTIC (regex `^\\s*root_agent\\s*=`), NOT a Python parser. It can
        yield a false positive on a commented-out assignment (`# root_agent = ...`) and a false
        negative on annotated or dynamic forms (`root_agent: Agent = ...`,
        `setattr(mod, "root_agent", ...)`).
        """
        if not self.exists(relative):
            return False
        return bool(_ROOT_AGENT_RE.search(self.read(relative)))
