"""`a2a` domain: Agent-to-Agent (A2A) interoperability around google-adk (P4b).

Three operations, all in the ``{ok, data, error}`` envelope:

1. ``consume(path, app_name, name, agent_card_url)`` — adds a ``remote_a2a`` agent (a
   ``RemoteA2aAgent(name=..., agent_card="<url>")`` proxy) to the project's sidecar and
   regenerates ``agent.py``. This proxy can then be composed as a ``sub_agent`` of another agent
   (``agents_compose``). **Codegen-only**: the toolkit never imports ``RemoteA2aAgent`` itself (the
   ``a2a`` extra is only required at the generated ``agent.py``'s *runtime*).

2. ``expose(path, app_name, port=8001, execute=False)`` — generates ``a2a_app.py`` in the app's
   folder (``a2a_app = to_a2a(root_agent, port=PORT)``), idempotent via :class:`Workspace`. By
   default (``execute=False``) returns the file path + the serve command
   (``uvicorn a2a_app:a2a_app``). If ``execute=True`` AND the ``a2a`` extra is present, starts a
   managed ``uvicorn`` process (via the :mod:`adk_toolkit_mcp.adk_cli` registry) serving on
   ``port`` and returns the agent-card URL.

3. ``agent_card(path, app_name)`` — best-effort: builds/inspects the project's ``root_agent``
   ``AgentCard`` via ``AgentCardBuilder`` (requires importing the agent + the ``a2a`` extra). Gates
   cleanly if the extra is absent (actionable ``err``, never a crash).

Tools exposed under ``namespace="a2a"`` → ``a2a_<name>``. BARE names. The ``a2a`` imports are
**lazy** and gated by ``importlib.util.find_spec("a2a")``. Cf.
``docs/adk-api-notes/a2a-mcp-bridge.md``: ``to_a2a(agent, *, host, port, ...) -> Starlette`` serves
``/.well-known/agent-card.json``; ``RemoteA2aAgent`` lives in
``google.adk.agents.remote_a2a_agent`` (NOT ``google.adk.agents``).
"""

from __future__ import annotations

import sys
from importlib.util import find_spec
from pathlib import Path
from typing import Any

from fastmcp import FastMCP

from .. import adk_cli
from ..envelope import err, ok
from ..project_model import (
    AgentSpec,
    ProjectModel,
    add_or_update_agent,
    is_identifier,
    load_model,
    regenerate,
    save_model,
    validate_spec,
)
from ..run_core import RootAgentImportError, import_root_agent
from ..workspace import Workspace

a2a_server: FastMCP = FastMCP("a2a")

#: app_name = Python package identifier (both folder AND module name).
_APP_NAME_ERR = (
    "Invalid app_name: expected a Python identifier "
    "(letters, digits, underscore; not starting with a digit)."
)

#: Name of the file generated by ``expose`` (in the app's folder).
_A2A_APP_FILE = "a2a_app.py"

#: Path of the agent-card well-known route (confirmed a2a-sdk constant).
_WELL_KNOWN_PATH = "/.well-known/agent-card.json"

#: Valid TCP port bounds.
_PORT_MIN = 1
_PORT_MAX = 65535

#: Folder of the managed processes' logs (reuses the dev domain's convention).
_LOG_DIR = ".adk_toolkit/logs"

#: Actionable message when the ``a2a`` extra is absent.
_A2A_EXTRA_ABSENT = (
    "The 'a2a' extra is not installed (the a2a-sdk package is not found). "
    "Install it: uv add 'adk-toolkit-mcp[a2a]' (or pip install 'google-adk[a2a]')."
)


# --------------------------------------------------------------------------- #
# Internal helpers (not exposed)
# --------------------------------------------------------------------------- #
def _app_ws(path: str, app_name: str) -> Workspace:
    """Workspace pointing at the app folder (``<path>/<app_name>``)."""
    return Workspace(Path(path) / app_name)


def _load(path: str, app_name: str) -> ProjectModel | dict[str, Any]:
    """Load the model; return an ``err(...)`` (dict) if the sidecar is corrupt."""
    try:
        return load_model(_app_ws(path, app_name), app_name)
    except ValueError as exc:
        return err(str(exc))


def _a2a_extra_present() -> bool:
    """True if the ``a2a`` extra (the ``a2a-sdk`` package) is importable."""
    return find_spec("a2a") is not None


def _validate_port(port: int) -> str | None:
    """Return an error message if ``port`` is out of the TCP bounds, otherwise None."""
    if not isinstance(port, int) or not (_PORT_MIN <= port <= _PORT_MAX):
        return f"Invalid port: {port!r}. Expected an integer in [{_PORT_MIN}, {_PORT_MAX}]."
    return None


def _a2a_app_source(port: int) -> str:
    """Source of ``a2a_app.py``: ``a2a_app = to_a2a(root_agent, port=PORT)``.

    Imports ``root_agent`` from the sibling module ``agent`` (the file is served with
    ``cwd=<app_dir>`` ⇒ ``uvicorn a2a_app:a2a_app`` resolves ``agent`` directly). The ``to_a2a``
    import requires the ``a2a`` extra at runtime — this is **codegen-only** (the toolkit does not
    import it to generate this file).

    Both imports (``agent`` and ``google.adk...``) are **third-party** from isort's point of view
    (neither is a first-party module known to ruff): they thus form ONE single group, sorted
    alphabetically and **without a blank line** separator — the output is ``ruff check --select I``
    clean (like the ``agent.py`` regenerated by ``consume``).
    """
    return (
        '"""Generated by adk-toolkit-mcp (a2a_expose). Serves the root_agent over A2A.\n'
        "\n"
        "Run:  uvicorn a2a_app:a2a_app --host localhost --port "
        f"{port}\n"
        f"The agent-card is served at {_WELL_KNOWN_PATH}.\n"
        "Requires the a2a extra: uv add 'adk-toolkit-mcp[a2a]'.\n"
        '"""\n'
        "\n"
        "from agent import root_agent\n"
        "from google.adk.a2a.utils.agent_to_a2a import to_a2a\n"
        "\n"
        f"a2a_app = to_a2a(root_agent, port={port})\n"
    )


def _log_path(path: str, app_name: str, port: int) -> str:
    """Path of the managed uvicorn process's log file (under the app's sidecar)."""
    return str(_app_ws(path, app_name).path(f"{_LOG_DIR}/a2a-{port}.log"))


# --------------------------------------------------------------------------- #
# consume — adds a RemoteA2aAgent proxy to the model
# --------------------------------------------------------------------------- #
@a2a_server.tool(tags={"a2a"})
def consume(path: str, app_name: str, name: str, agent_card_url: str) -> dict[str, Any]:
    """Add a ``remote_a2a`` agent (``RemoteA2aAgent`` proxy) and regenerate ``agent.py``.

    ``name`` is the identifier of the generated agent variable; ``agent_card_url`` is the URL (or
    local JSON path) of the remote A2A service's agent-card. The proxy has no children but can be
    composed as a ``sub_agent`` of another agent afterwards (via ``agents_compose``).

    Returns the common payload ``{app_name, agents, root, sidecar, regenerated, changed}``. Invalid
    inputs (app_name/name not identifiers, empty URL) → ``err``. Codegen-only: no ``a2a``
    dependency is required to ADD the proxy (only to run the ``agent.py``).
    """
    if not is_identifier(app_name):
        return err(_APP_NAME_ERR)
    if not is_identifier(name):
        return err(f"Invalid agent name: {name!r}. Expected a Python identifier.")
    if not agent_card_url.strip():
        return err(
            "agent_card_url is empty. Provide the URL (or JSON path) of the remote agent-card "
            "(e.g. 'http://host:8001/.well-known/agent-card.json')."
        )

    spec = AgentSpec(name=name, type="remote_a2a", agent_card=agent_card_url.strip())
    spec_error = validate_spec(spec)
    if spec_error is not None:
        return err(spec_error)

    model = _load(path, app_name)
    if isinstance(model, dict):  # err()
        return model

    model = add_or_update_agent(model, spec)
    ws = _app_ws(path, app_name)
    try:
        regen = regenerate(ws, model)
    except ValueError as exc:  # cycle (unlikely for a childless proxy)
        return err(str(exc))
    sidecar_changed = save_model(ws, model)
    return ok(
        {
            "app_name": app_name,
            "agents": list(model.agent_names()),
            "root": model.root,
            "remote_agent": {"name": name, "agent_card": agent_card_url.strip()},
            "sidecar": str(ws.path(".adk_toolkit/agents.json")),
            "regenerated": {"agent_py": regen["agent_py"], "init_py": regen["init_py"]},
            "changed": bool(regen["changed"]) or sidecar_changed,
        }
    )


# --------------------------------------------------------------------------- #
# expose — generates a2a_app.py; optionally serves via uvicorn (managed process)
# --------------------------------------------------------------------------- #
@a2a_server.tool(tags={"a2a"})
def expose(path: str, app_name: str, port: int = 8001, execute: bool = False) -> dict[str, Any]:
    """Generate ``a2a_app.py`` (``to_a2a(root_agent, port=PORT)``); optionally serve via uvicorn.

    Writes ``<path>/<app_name>/a2a_app.py`` (idempotent via :class:`Workspace`). Then:

    - ``execute=False`` (default): returns ``{file, serve_command, agent_card_path, executed:
      False}`` (the ``uvicorn a2a_app:a2a_app`` command to run from the app's folder). NO ``a2a``
      dependency required (codegen-only).
    - ``execute=True``: requires the ``a2a`` extra (otherwise an actionable ``err``). Starts a
      managed ``uvicorn a2a_app:a2a_app --host localhost --port <port>`` process (adk_cli registry,
      cwd = the app's folder to resolve the ``agent`` import) and returns ``{key, pid, url,
      agent_card_url, executed: True, ...}``.
    """
    if not is_identifier(app_name):
        return err(_APP_NAME_ERR)
    port_error = _validate_port(port)
    if port_error is not None:
        return err(port_error)

    ws = _app_ws(path, app_name)
    app_dir = ws.root
    if not app_dir.is_dir():
        return err(f"App folder not found: {app_dir}. Scaffold the app first (project_create).")
    if not ws.exists("agent.py"):
        return err(
            f"agent.py not found in {app_dir}. Create a root_agent first "
            "(agents_create_llm + agents_set_root)."
        )

    changed = ws.write(_A2A_APP_FILE, _a2a_app_source(port))
    file_path = str(ws.path(_A2A_APP_FILE))
    serve_command = f"uvicorn a2a_app:a2a_app --host localhost --port {port}"

    if not execute:
        return ok(
            {
                "file": file_path,
                "changed": changed,
                "port": port,
                "serve_command": serve_command,
                "serve_cwd": str(app_dir),
                "agent_card_path": _WELL_KNOWN_PATH,
                "executed": False,
                "note": (
                    "Run the command from 'serve_cwd' (the app's folder). Requires the a2a "
                    "extra: uv add 'adk-toolkit-mcp[a2a]'."
                ),
            }
        )

    if not _a2a_extra_present():
        return err(_A2A_EXTRA_ABSENT)

    # uvicorn in the current venv + the importable app (cwd = the app's folder).
    argv = [
        sys.executable,
        "-m",
        "uvicorn",
        "a2a_app:a2a_app",
        "--host",
        "localhost",
        "--port",
        str(port),
    ]
    key = adk_cli.make_key("a2a", str(app_dir), port)
    try:
        info = adk_cli.start_process(
            key, argv, cwd=str(app_dir), log_path=_log_path(path, app_name, port)
        )
    except adk_cli.ProcessAlreadyRunning as exc:
        return err(str(exc))

    return ok(
        {
            "file": file_path,
            "key": info["key"],
            "pid": info["pid"],
            "running": info["running"],
            "port": port,
            "url": f"http://localhost:{port}",
            "agent_card_url": f"http://localhost:{port}{_WELL_KNOWN_PATH}",
            "log_path": info["log_path"],
            "serve_command": serve_command,
            "executed": True,
        }
    )


# --------------------------------------------------------------------------- #
# agent_card — best-effort build of the root_agent's AgentCard
# --------------------------------------------------------------------------- #
@a2a_server.tool(tags={"a2a"})
async def agent_card(path: str, app_name: str, port: int = 8001) -> dict[str, Any]:
    """Build/inspect the project's ``root_agent`` ``AgentCard`` (best-effort, ``a2a``-gated).

    Requires (a) the ``a2a`` extra and (b) importing the project's ``root_agent``. If the extra is
    absent → actionable ``err`` (no crash). Otherwise, imports the agent, builds the card via
    ``AgentCardBuilder(agent=..., rpc_url="http://localhost:<port>/")`` (``build()`` is async) and
    returns ``card.model_dump(exclude_none=True)`` (name/description/url/skills/capabilities/...).

    ``port`` is only used to compose the ``rpc_url`` written into the card (no server is launched).
    """
    if not is_identifier(app_name):
        return err(_APP_NAME_ERR)
    if not _a2a_extra_present():
        return err(_A2A_EXTRA_ABSENT)

    try:
        root_agent = import_root_agent(path, app_name)
    except RootAgentImportError as exc:
        return err(str(exc))

    try:
        from google.adk.a2a.utils.agent_card_builder import AgentCardBuilder

        builder = AgentCardBuilder(agent=root_agent, rpc_url=f"http://localhost:{port}/")
        card = await builder.build()
        card_dict = (
            card.model_dump(exclude_none=True) if hasattr(card, "model_dump") else dict(vars(card))
        )
    except Exception as exc:  # noqa: BLE001 - best-effort build, we return a clean err
        return err(f"Failed to build the AgentCard: {exc}")

    return ok(
        {
            "app_name": app_name,
            "agent_card": card_dict,
            "well_known_path": _WELL_KNOWN_PATH,
        }
    )
