"""Generation of ``otel_setup.py``: real OpenTelemetry configuration (ast-valid, P4c).

A **pure** module (no dependency on OpenTelemetry at load: we only produce a *source string*). The
``observability`` domain (``observability_enable_otel``) uses it to write
``<app_dir>/<app>/otel_setup.py``. The generated file defines ``setup_otel()`` which installs a
GLOBAL ``TracerProvider`` (the one that ADK's telemetry uses for its spans), with:

- a ``Resource`` carrying ``service.name=<app>``;
- a ``BatchSpanProcessor`` wired onto the chosen exporter:
  - ``console``: ``ConsoleSpanExporter`` (base OTel SDK package — always available);
  - ``otlp``: ``OTLPSpanExporter`` (HTTP) imported **lazily** INSIDE ``setup_otel`` (separate
    package ``opentelemetry-exporter-otlp`` — a clear ``ImportError`` guides the install).

The base SDK imports (``trace``, ``TracerProvider``, ``BatchSpanProcessor``,
``ConsoleSpanExporter``, ``Resource``, ``SERVICE_NAME``) are confirmed present with ``google-adk``
(cf. ``docs/adk-api-notes/safety-observability.md``). The generated code is **ast.parse + ruff
format + isort clean** (verified in tests).
"""

from __future__ import annotations

#: Header of the generated module.
_HEADER = (
    '"""OpenTelemetry configuration generated by adk-toolkit-mcp (observability_enable_otel).\n\n'
    "Call ``setup_otel()`` at startup (before running the agent): it installs the\n"
    "GLOBAL ``TracerProvider`` that ADK uses to emit its spans.\n"
    '"""\n\n'
)

#: Common imports (base OTel SDK — available with google-adk).
_BASE_IMPORTS = (
    "from opentelemetry import trace\n"
    "from opentelemetry.sdk.resources import SERVICE_NAME, Resource\n"
    "from opentelemetry.sdk.trace import TracerProvider\n"
    "from opentelemetry.sdk.trace.export import BatchSpanProcessor\n"
)


def _py_str(value: str) -> str:
    """Python string literal stable for ``ruff format`` (double quotes by default)."""
    has_double = '"' in value
    has_single = "'" in value
    if has_double and not has_single:
        return "'" + value.replace("\\", "\\\\") + "'"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _console_exporter_lines() -> tuple[str, str]:
    """Return ``(extra_import, body_lines)`` for the console exporter.

    The ``ConsoleSpanExporter`` import is grouped with the other SDK imports (top-level); the body
    simply instantiates the exporter.
    """
    extra_import = "from opentelemetry.sdk.trace.export import ConsoleSpanExporter\n"
    body = "    exporter = ConsoleSpanExporter()\n"
    return extra_import, body


def _otlp_exporter_lines(endpoint: str) -> tuple[str, str]:
    """Return ``(extra_import, body_lines)`` for the OTLP/HTTP exporter.

    The import is done **lazily INSIDE** ``setup_otel`` (separate package) with an actionable error
    message; ``endpoint`` is injected as a literal. No top-level import (the OTLP package may be
    absent — the file must stay importable).
    """
    extra_import = ""  # lazy import in the body (separate package, may be absent)
    body = (
        "    try:\n"
        "        from opentelemetry.exporter.otlp.proto.http.trace_exporter import (\n"
        "            OTLPSpanExporter,\n"
        "        )\n"
        "    except ImportError as exc:  # separate package\n"
        "        raise ImportError(\n"
        '            "OTLP exporter missing: pip install opentelemetry-exporter-otlp"\n'
        "        ) from exc\n"
        f"    exporter = OTLPSpanExporter(endpoint={_py_str(endpoint)})\n"
    )
    return extra_import, body


def render_otel_setup(*, app_name: str, exporter: str, endpoint: str | None) -> str:
    """Produce the complete source of ``otel_setup.py`` for the chosen exporter.

    ``exporter`` ∈ {``console``, ``otlp``}. For ``otlp``, ``endpoint`` is required (validated
    upstream by the domain). ast-valid + ruff/isort-clean output.
    """
    if exporter == "otlp":
        extra_import, exporter_body = _otlp_exporter_lines(endpoint or "")
    else:
        extra_import, exporter_body = _console_exporter_lines()

    # Import section: base + an optional console import (grouped/sorted isort-style). All under
    # ``opentelemetry.*`` -> a single third-party block; the names of a same module sorted by hand
    # here (SERVICE_NAME before Resource; see _BASE_IMPORTS). We insert ConsoleSpanExporter into
    # the ``...export import BatchSpanProcessor`` line to stay isort-clean.
    imports = _merge_imports(extra_import)

    func = (
        "def setup_otel() -> TracerProvider:\n"
        '    """Install a global TracerProvider exporting the ADK spans; return it."""\n'
        f"    resource = Resource.create({{SERVICE_NAME: {_py_str(app_name)}}})\n"
        "    provider = TracerProvider(resource=resource)\n"
        f"{exporter_body}"
        "    provider.add_span_processor(BatchSpanProcessor(exporter))\n"
        "    trace.set_tracer_provider(provider)\n"
        "    return provider\n"
    )
    return _HEADER + imports + "\n\n" + func


def _merge_imports(extra_console_import: str) -> str:
    """Merge the SDK imports (+ an optional ConsoleSpanExporter) isort-style (stable for ruff).

    ``BatchSpanProcessor`` and ``ConsoleSpanExporter`` share the module
    ``opentelemetry.sdk.trace.export``: we put them on a single line, names sorted
    (``BatchSpanProcessor`` < ``ConsoleSpanExporter``). The other lines of :data:`_BASE_IMPORTS`
    are kept as-is (already sorted by module + by name).
    """
    if not extra_console_import:
        return _BASE_IMPORTS
    # Replace the base export line with a merged, sorted line.
    base = _BASE_IMPORTS.replace(
        "from opentelemetry.sdk.trace.export import BatchSpanProcessor\n",
        "from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter\n",
    )
    return base
