"""Generation of ``plugins.py``: real ``BasePlugin`` subclasses (global policies, P4c).

A **pure** module (no dependency on google-adk: we only produce a *source string*). The
``safety`` domain (``safety_add_plugin``) uses it to (re)generate ``<app_dir>/<app>/plugins.py``
from a plugin manifest, then ``run_core.build_runner`` imports those instances and passes them to
the ``Runner`` (via ``App``).

Two concrete + functional global policies (cf. ``docs/adk-api-notes/safety-observability.md`` for
the confirmed ``BasePlugin`` hook signatures — **keyword-only**, async hooks):

- ``logging``: ``on_event_callback`` records the author of each event in a module-level
  ``<var>_events`` list (offline-inspectable, which enables the functional PROOF) and logs via the
  ``logging`` module.
- ``tool_denylist``: ``before_tool_callback`` short-circuits any tool call whose name is in a
  denylist (returns a ``dict`` → the tool is never executed).

The generated code is **ast.parse + ruff format + isort clean** (verified in tests).
"""

from __future__ import annotations

import re
from typing import Any

#: Header of the generated module (do not edit by hand: regenerated from the runtime manifest).
_HEADER = (
    '"""Generated by adk-toolkit-mcp (safety_add_plugin). DO NOT edit by hand.\n\n'
    "BasePlugin plugins declared at module level; the manifest lives in "
    "`.adk_toolkit/runtime.json`\n"
    "(`plugins` key). `run_core.build_runner` imports these instances and passes them to Runner.\n"
    '"""\n\n'
)

#: PascalCase plugin class for a variable (``logging_plugin`` -> ``LoggingPluginPlugin``).
_CLASS_SUFFIX = "Plugin"


def _py_str(value: str) -> str:
    """Python string literal stable for ``ruff format`` (double quotes by default)."""
    has_double = '"' in value
    has_single = "'" in value
    if has_double and not has_single:
        return "'" + value.replace("\\", "\\\\") + "'"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _py_str_list(values: list[str]) -> str:
    """Render ``["a", "b"]`` (string list literal) inline and ruff-stable."""
    return "[" + ", ".join(_py_str(v) for v in values) + "]"


def _class_name(var: str) -> str:
    """PascalCase class name from the variable name (``my_plugin`` -> ``MyPluginPlugin``)."""
    pascal = "".join(part.capitalize() for part in var.split("_") if part)
    if not pascal:
        pascal = "Custom"
    return f"{pascal}{_CLASS_SUFFIX}"


def _render_logging_plugin(var: str, name: str) -> list[str]:
    """Render the top-level blocks of a ``logging`` plugin (``on_event_callback``).

    Returns ``[events_assignment, class_block, instance_block]``. A module-level ``<var>_events``
    list accumulates the author of each event (offline functional proof); the hook also logs via
    ``logging.getLogger(__name__)``.
    """
    cls = _class_name(var)
    events_var = f"{var}_events"
    events_block = f"{events_var}: list[str] = []\n"
    class_block = (
        f"class {cls}(BasePlugin):\n"
        '    """Logging plugin: records each event (author) and logs it."""\n'
        "\n"
        "    async def on_event_callback(self, *, invocation_context, event):\n"
        f"        {events_var}.append(event.author)\n"
        '        logging.getLogger(__name__).info("event from %s", event.author)\n'
        "        return None\n"
    )
    instance_block = f"{var} = {cls}(name={_py_str(name)})\n"
    return [events_block, class_block, instance_block]


def _render_tool_denylist_plugin(var: str, name: str, denylist: list[str]) -> list[str]:
    """Render the top-level blocks of a ``tool_denylist`` plugin (global ``before_tool_callback``).

    Short-circuits any tool call whose name is in ``denylist`` (returns a ``dict``). Returns
    ``[denylist_assignment, class_block, instance_block]``.
    """
    cls = _class_name(var)
    denylist_var = f"{var}_denylist"
    denylist_block = f"{denylist_var} = {_py_str_list(denylist)}\n"
    blocked = _py_str("Tool blocked by global safety plugin.")
    class_block = (
        f"class {cls}(BasePlugin):\n"
        '    """Global denylist plugin: short-circuits any tool whose name is forbidden."""\n'
        "\n"
        "    async def before_tool_callback(self, *, tool, tool_args, tool_context):\n"
        f"        if tool.name in {denylist_var}:\n"
        f"            return {{{_py_str('error')}: {blocked}}}\n"
        "        return None\n"
    )
    instance_block = f"{var} = {cls}(name={_py_str(name)})\n"
    return [denylist_block, class_block, instance_block]


def _render_one(payload: dict[str, Any]) -> list[str]:
    """Dispatch to the renderer for the right ``kind``; return the list of top-level blocks."""
    var = str(payload["var"])
    name = str(payload.get("name") or var)
    kind = str(payload["kind"])
    if kind == "logging":
        return _render_logging_plugin(var, name)
    if kind == "tool_denylist":
        denylist = [str(x) for x in payload.get("denylist") or []]
        return _render_tool_denylist_plugin(var, name, denylist)
    raise ValueError(f"Unrendered plugin kind: {kind!r}")  # pragma: no cover


def _starts_class_or_def(block: str) -> bool:
    """True if the top-level block starts with ``class`` or ``def`` (E302/E305 spacing rule)."""
    return block.startswith("class ") or block.startswith("def ")


def _space_blocks(blocks: list[str]) -> str:
    """Assemble top-level blocks with the exact ``ruff format`` spacing (E302/E303/E305).

    2 blank lines around a ``class``/``def`` block; 1 blank line between two assignments. Each
    block already ends with exactly one ``\\n``.
    """
    parts: list[str] = []
    for i, block in enumerate(blocks):
        parts.append(block)
        if i < len(blocks) - 1:
            nxt = blocks[i + 1]
            parts.append(
                "\n\n" if _starts_class_or_def(block) or _starts_class_or_def(nxt) else "\n"
            )
    return "".join(parts)


def render_plugins_module(payloads: list[dict[str, Any]]) -> str:
    """Produce the complete source of ``plugins.py`` from the plugin payloads.

    Each payload: ``{"var", "name", "kind", "denylist"?}``. The imports (``logging`` stdlib +
    ``BasePlugin``) are emitted according to the kinds present (isort: stdlib before third-party).
    The blocks are spaced ``ruff format``-style (2 blank lines around top-level classes).
    """
    if not payloads:
        # No plugin: minimal valid module (degenerate case; the domain does not call it this way).
        return _HEADER + "# No plugin declared.\n"

    kinds = {str(p["kind"]) for p in payloads}
    needs_logging = "logging" in kinds

    # Imports: stdlib (``import logging``) before third-party (``from google.adk.plugins ...``).
    import_lines: list[str] = []
    if needs_logging:
        import_lines.append("import logging")
        import_lines.append("")  # blank line between stdlib and third-party (isort)
    import_lines.append("from google.adk.plugins import BasePlugin")
    import_block = "\n".join(import_lines) + "\n"

    # Flatten all the blocks (assignment + class + instance per plugin) then space ruff-style.
    all_blocks: list[str] = [b for payload in payloads for b in _render_one(payload)]
    body = _space_blocks(all_blocks)

    # The 1st top-level block always starts with an ASSIGNMENT (events/denylist): isort/ruff
    # requires only ONE blank line after the import block before an assignment (2 would be required
    # only before a class/def). So we emit a single blank line here.
    return _HEADER + import_block + "\n" + body


#: Regex to re-read an existing plugin's ``denylist`` (best-effort, during a regeneration).
_DENYLIST_RE = re.compile(r"^(\w+)_denylist = (\[.*\])$", re.MULTILINE)


def parse_existing_denylists(source: str) -> dict[str, list[str]]:
    """Re-read the ``tool_denylist`` plugins' denylists from an existing ``plugins.py``.

    Returns ``{var: [tool, ...]}``. Used to preserve the config of already-present plugins during a
    full regeneration of the file. Tolerant: an unrecognized line is ignored.
    """
    out: dict[str, list[str]] = {}
    for match in _DENYLIST_RE.finditer(source):
        var = match.group(1)
        raw_list = match.group(2)
        items = re.findall(r'"([^"]*)"|\'([^\']*)\'', raw_list)
        out[var] = [a or b for a, b in items]
    return out
