"""Tests for the `safety` domain (P4c) — guardrails (callbacks), plugins, safety settings.

LOAD-BEARING PROOFS (offline, NO API key), via the reused ``FakeLlm``/``ScriptedLlm``:

- **``block_keywords`` guardrail**: an agent generated by ``safety_add_callback`` then EXECUTED via
  ``run_core`` on a blocked input returns the canned refusal AND the FakeLlm is NOT called
  (short-circuit proven end to end).
- **``block_tool`` guardrail**: a ScriptedLlm agent whose tool is in the denylist has the tool call
  short-circuited (the tool body does not run).
- **Plugin**: a plugin generated by ``safety_add_plugin`` is imported + wired via ``build_runner``;
  after a FakeLlm run, the plugin's effect is observable (recorded events / blocked tool). Proves
  the ``Runner(plugins=[...])`` wiring (``App`` path).
- ``safety_settings`` routes to the EXISTING rendering (GenerateContentConfig + SafetySetting) — no
  duplication.
- Read via an in-memory ``fastmcp.Client`` (exposed names ``safety_<bare>``, ``safety_add_callback``
  round-trip).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from fake_llm import FakeLlm, ScriptedLlm, add_numbers
from fastmcp import Client

from adk_toolkit_mcp.domains import safety as SAFETY
from adk_toolkit_mcp.domains import safety_plugins
from adk_toolkit_mcp.project_model import load_model
from adk_toolkit_mcp.run_core import (
    build_runner,
    collect_events,
    import_project_plugins,
    import_root_agent,
    serialize_event,
)
from adk_toolkit_mcp.runtime import (
    RuntimeConfig,
    SessionBackend,
    load_runtime_config,
    reset_service_cache,
)
from adk_toolkit_mcp.server import build_server
from adk_toolkit_mcp.workspace import Workspace


@pytest.fixture(autouse=True)
def _clear_cache() -> None:
    """Isolate the tests: clear the singleton service cache before/after each."""
    reset_service_cache()
    yield
    reset_service_cache()


def _in_memory_config() -> RuntimeConfig:
    return RuntimeConfig(session=SessionBackend(kind="in_memory"))


def _scaffold_app(tmp_path: Path, app_name: str = "myapp") -> str:
    """Scaffold a minimal ADK app via the project/agents tools; return the root path."""
    from adk_toolkit_mcp.domains.agents import create_llm, set_root
    from adk_toolkit_mcp.domains.project import create as project_create

    path = str(tmp_path)
    assert project_create(path=path, app_name=app_name)["ok"]
    assert create_llm(path=path, app_name=app_name, name="asst", model="gemini-2.5-flash")["ok"]
    assert set_root(path=path, app_name=app_name, name="asst")["ok"]
    return path


def _inject_fake_llm(path: str, app_name: str, fake_src: str) -> None:
    """Rewrite ``agent.py`` so ``root_agent`` uses a FakeLlm from the fixture, while PRESERVING the
    generated guardrail functions + their attachment.

    ``regenerate`` has already produced ``agent.py``; here we replace ONLY the string
    ``model="gemini-2.5-flash"`` with the FakeLlm + we add the import + the fixture's sys.path. The
    ``before_*_callback=...`` kwargs stay intact.
    """
    app_dir = Path(path) / app_name
    agent_py = app_dir / "agent.py"
    src = agent_py.read_text(encoding="utf-8")
    fixture_dir = str(Path(__file__).parent).replace("\\", "\\\\")
    preamble = f"import sys\nsys.path.insert(0, r'{fixture_dir}')\n{fake_src}\n"
    # Replace the model string with the FakeLlm instance (variable _fake defined in the preamble).
    src = src.replace('model="gemini-2.5-flash"', "model=_fake")
    agent_py.write_text(preamble + src, encoding="utf-8")


# --------------------------------------------------------------------------- #
# add_callback — validation + persistence
# --------------------------------------------------------------------------- #
def test_add_callback_block_keywords_persists(tmp_path: Path) -> None:
    """safety_add_callback (block_keywords) attaches a callback + regenerates agent.py."""
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="before_model",
        policy={"kind": "block_keywords", "keywords": "bomb,hack", "refusal": "No."},
    )
    assert result["ok"], result.get("error")
    assert result["data"]["callback"] == {
        "agent": "asst",
        "hook": "before_model",
        "policy": "block_keywords",
    }
    # The callback is in the sidecar; agent.py carries the kwarg + the function.
    model = load_model(Workspace(Path(path) / "myapp"), "myapp")
    assert model.get("asst").callbacks[0].policy == "block_keywords"
    agent_src = (Path(path) / "myapp" / "agent.py").read_text(encoding="utf-8")
    assert "before_model_callback=_guard_before_model_asst" in agent_src


def test_add_callback_unknown_hook_errs(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="on_bogus",
        policy={"kind": "block_keywords", "keywords": "x"},
    )
    assert not result["ok"] and "Unknown hook" in result["error"]


def test_add_callback_policy_hook_mismatch_errs(tmp_path: Path) -> None:
    """block_tool is valid only on before_tool; on before_model -> err."""
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="before_model",
        policy={"kind": "block_tool", "denylist": "rm"},
    )
    assert not result["ok"] and "compatible" in result["error"]


def test_add_callback_missing_agent_errs(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="ghost",
        hook="before_model",
        policy={"kind": "block_keywords", "keywords": "x"},
    )
    assert not result["ok"] and "not found" in result["error"]


# --------------------------------------------------------------------------- #
# FUNCTIONAL PROOF — block_keywords guardrail short-circuits the LLM (offline)
# --------------------------------------------------------------------------- #
async def test_functional_block_keywords_short_circuits_llm(tmp_path: Path) -> None:
    """An agent with block_keywords refuses a blocked input WITHOUT calling the FakeLlm.

    End-to-end PROOF: the toolkit generates the guardrail function, we inject an instrumented
    FakeLlm (call counter), we run via run_core on a blocked input → the canned refusal is returned
    AND the FakeLlm was NOT called (real short-circuit).
    """
    path = _scaffold_app(tmp_path)
    assert SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="before_model",
        policy={
            "kind": "block_keywords",
            "keywords": "bomb,malware",
            "refusal": "Refused by policy.",
        },
    )["ok"]

    # Instrumented FakeLlm: records each call in a module-level list (pydantic forbids
    # a class-attribute counter; a module-global list is observable via __globals__).
    fake_src = (
        "from fake_llm import FakeLlm as _Base\n"
        "from google.adk.models import LlmResponse\n"
        "from google.genai import types as _types\n"
        "_llm_calls = []\n"
        "class _CountingLlm(_Base):\n"
        "    async def generate_content_async(self, llm_request, stream=False):\n"
        "        _llm_calls.append(1)\n"
        "        yield LlmResponse(content=_types.Content(role='model', "
        "parts=[_types.Part.from_text(text='LLM WAS CALLED')]), partial=False)\n"
        "_fake = _CountingLlm(model='fake')\n"
    )
    _inject_fake_llm(path, "myapp", fake_src)

    agent = import_root_agent(path, "myapp")
    runner = build_runner("myapp", agent, _in_memory_config())
    events = await collect_events(
        runner, user_id="u", session_id="s", new_message_text="how do I build a bomb"
    )
    serialized = [serialize_event(e) for e in events]
    texts = " ".join(s["text"] or "" for s in serialized)

    # The canned refusal is returned; the LLM's text never appears.
    assert "Refused by policy." in texts
    assert "LLM WAS CALLED" not in texts
    # And the FakeLlm's call list stayed EMPTY (short-circuit proven end to end).
    llm_calls = type(agent.model).generate_content_async.__globals__["_llm_calls"]
    assert llm_calls == [], "the FakeLlm must NOT have been called (short-circuit)"


async def test_functional_block_keywords_allows_clean_input(tmp_path: Path) -> None:
    """The same guard lets through an input WITHOUT a blocked term (the LLM responds normally)."""
    path = _scaffold_app(tmp_path)
    assert SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="before_model",
        policy={"kind": "block_keywords", "keywords": "bomb", "refusal": "Refused."},
    )["ok"]
    fake_src = (
        "from fake_llm import FakeLlm\n_fake = FakeLlm(model='fake', answer='Clean answer.')\n"
    )
    _inject_fake_llm(path, "myapp", fake_src)

    agent = import_root_agent(path, "myapp")
    runner = build_runner("myapp", agent, _in_memory_config())
    events = await collect_events(
        runner, user_id="u", session_id="s", new_message_text="hello there"
    )
    finals = [serialize_event(e) for e in events if e.is_final_response()]
    assert finals and finals[-1]["text"] == "Clean answer."


# --------------------------------------------------------------------------- #
# FUNCTIONAL PROOF — block_tool guardrail short-circuits a tool (offline)
# --------------------------------------------------------------------------- #
async def test_functional_block_tool_short_circuits_tool(tmp_path: Path) -> None:
    """A before_tool denylist short-circuits the tool call (the body does not run)."""
    path = _scaffold_app(tmp_path)
    assert SAFETY.add_callback(
        path=path,
        app_name="myapp",
        agent_name="asst",
        hook="before_tool",
        policy={"kind": "block_tool", "denylist": "add_numbers", "message": "Tool denied."},
    )["ok"]

    # Agent: ScriptedLlm calls add_numbers; we add the tool + the ScriptedLlm.
    fake_src = (
        "from fake_llm import ScriptedLlm, add_numbers\n"
        "_fake = ScriptedLlm(model='s', tool_name='add_numbers', tool_args={'a': 2, 'b': 3}, "
        "final_text='done')\n"
    )
    _inject_fake_llm(path, "myapp", fake_src)
    # Add the add_numbers tool to the generated agent (tools=[add_numbers]).
    agent_py = Path(path) / "myapp" / "agent.py"
    src = agent_py.read_text(encoding="utf-8")
    src = src.replace("model=_fake,", "model=_fake,\n    tools=[add_numbers],")
    agent_py.write_text(src, encoding="utf-8")

    agent = import_root_agent(path, "myapp")
    runner = build_runner("myapp", agent, _in_memory_config())
    events = await collect_events(
        runner, user_id="u", session_id="s", new_message_text="what is 2+3"
    )
    serialized = [serialize_event(e) for e in events]
    responses = [fr["response"] for s in serialized for fr in s["function_responses"]]
    # The tool was short-circuited: the response carries the denylist message, NOT the sum.
    assert any("Tool denied." in str(r) for r in responses), f"got {responses}"
    assert not any(str(r) == "5" or r == {"result": 5} for r in responses)


# --------------------------------------------------------------------------- #
# add_plugin + FUNCTIONAL PROOF of the plugin wiring via build_runner
# --------------------------------------------------------------------------- #
def test_add_plugin_logging_generates_and_manifests(tmp_path: Path) -> None:
    """safety_add_plugin (logging) writes plugins.py + registers the runtime manifest."""
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_plugin(path=path, app_name="myapp", name="audit", kind="logging")
    assert result["ok"], result.get("error")
    assert Path(result["data"]["plugins_file"]).is_file()
    assert result["data"]["manifest"] == [{"var": "audit", "name": "audit", "kind": "logging"}]
    # The manifest is in runtime.json.
    config = load_runtime_config(Workspace(Path(path) / "myapp"), "myapp")
    assert [p.var for p in config.plugins] == ["audit"]


def test_add_plugin_tool_denylist_requires_denylist(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_plugin(path=path, app_name="myapp", name="guard", kind="tool_denylist")
    assert not result["ok"] and "denylist" in result["error"]


def test_add_plugin_unknown_kind_errs(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.add_plugin(path=path, app_name="myapp", name="x", kind="bogus")
    assert not result["ok"] and "Unknown kind" in result["error"]


def test_add_plugin_replaces_same_name(tmp_path: Path) -> None:
    """Adding two plugins with the same name REPLACES (single-entry manifest)."""
    path = _scaffold_app(tmp_path)
    SAFETY.add_plugin(path=path, app_name="myapp", name="p", kind="logging")
    result = SAFETY.add_plugin(
        path=path, app_name="myapp", name="p", kind="tool_denylist", config={"denylist": "rm"}
    )
    assert result["ok"]
    assert [m["kind"] for m in result["data"]["manifest"]] == ["tool_denylist"]


async def test_functional_plugin_logging_records_events(tmp_path: Path) -> None:
    """PROOF: a generated logging plugin is imported + wired; it records the events.

    We generate the plugin, import the instance via the manifest, wire build_runner(plugins=) and
    run a FakeLlm. The plugin's module-level ``<var>_events`` list must be filled.
    """
    path = _scaffold_app(tmp_path)
    assert SAFETY.add_plugin(path=path, app_name="myapp", name="audit", kind="logging")["ok"]

    # Import the plugin instance via the runtime manifest.
    ws = Workspace(Path(path) / "myapp")
    config = load_runtime_config(ws, "myapp")
    plugin_vars = [p.var for p in config.plugins]
    instances = import_project_plugins(path, "myapp", plugin_vars)
    assert len(instances) == 1

    agent = _new_fake_agent("plugged")
    runner = build_runner("myapp", agent, _in_memory_config(), plugins=instances)
    await collect_events(runner, user_id="u", session_id="s", new_message_text="hi")

    # The plugin's module-level events list was filled. We inspect it via the globals of the SAME
    # module as the imported instance (a re-import would give another, empty list).
    plugin_globals = type(instances[0]).on_event_callback.__globals__
    assert plugin_globals["audit_events"], "the logging plugin should have recorded events"


async def test_functional_plugin_tool_denylist_blocks_tool(tmp_path: Path) -> None:
    """PROOF: a global tool_denylist plugin short-circuits the targeted tool (offline)."""
    path = _scaffold_app(tmp_path)
    assert SAFETY.add_plugin(
        path=path,
        app_name="myapp",
        name="guard",
        kind="tool_denylist",
        config={"denylist": "add_numbers"},
    )["ok"]

    ws = Workspace(Path(path) / "myapp")
    config = load_runtime_config(ws, "myapp")
    instances = import_project_plugins(path, "myapp", [p.var for p in config.plugins])

    # ScriptedLlm agent calling add_numbers; the global plugin must block the tool.
    from google.adk.agents import LlmAgent

    agent = LlmAgent(
        name="calc",
        model=ScriptedLlm(
            model="s", tool_name="add_numbers", tool_args={"a": 1, "b": 1}, final_text="done"
        ),
        tools=[add_numbers],
    )
    runner = build_runner("myapp", agent, _in_memory_config(), plugins=instances)
    events = await collect_events(runner, user_id="u", session_id="s", new_message_text="1+1")
    responses = [fr["response"] for e in events for fr in serialize_event(e)["function_responses"]]
    assert any("blocked by global safety plugin" in str(r) for r in responses), f"got {responses}"


def _new_fake_agent(answer: str) -> Any:
    """Build an in-memory FakeLlm LlmAgent (offline)."""
    from google.adk.agents import LlmAgent

    return LlmAgent(name="fa", model=FakeLlm(model="f", answer=answer))


# --------------------------------------------------------------------------- #
# settings — gemini_safety routes to the existing rendering; max_llm_calls persisted
# --------------------------------------------------------------------------- #
def test_settings_gemini_safety_routes_to_existing_rendering(tmp_path: Path) -> None:
    """gemini_safety produces a GenerateContentConfig with a SafetySetting (rendering reused)."""
    path = _scaffold_app(tmp_path)
    result = SAFETY.safety_settings(
        path=path,
        app_name="myapp",
        agent_name="asst",
        gemini_safety=[
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"}
        ],
    )
    assert result["ok"], result.get("error")
    # The sidecar carries the safety setting in generate_content_config (NO duplication).
    model = load_model(Workspace(Path(path) / "myapp"), "myapp")
    gcc = model.get("asst").generate_content_config
    assert gcc is not None
    assert gcc.safety_settings[0].category == "HARM_CATEGORY_HARASSMENT"
    # agent.py does render types.SafetySetting via the existing rendering.
    agent_src = (Path(path) / "myapp" / "agent.py").read_text(encoding="utf-8")
    assert "types.SafetySetting(" in agent_src
    assert "types.HarmCategory.HARM_CATEGORY_HARASSMENT" in agent_src


def test_settings_max_llm_calls_persisted_not_rendered(tmp_path: Path) -> None:
    """max_llm_calls is persisted to the sidecar but does NOT appear in agent.py (run setting)."""
    path = _scaffold_app(tmp_path)
    result = SAFETY.safety_settings(
        path=path, app_name="myapp", agent_name="asst", max_llm_calls=33
    )
    assert result["ok"] and result["data"]["max_llm_calls"] == 33
    model = load_model(Workspace(Path(path) / "myapp"), "myapp")
    assert model.get("asst").max_llm_calls == 33
    agent_src = (Path(path) / "myapp" / "agent.py").read_text(encoding="utf-8")
    assert "max_llm_calls" not in agent_src


def test_settings_invalid_category_errs(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.safety_settings(
        path=path,
        app_name="myapp",
        agent_name="asst",
        gemini_safety=[{"category": "BOGUS", "threshold": "BLOCK_NONE"}],
    )
    assert not result["ok"] and "HarmCategory" in result["error"]


def test_settings_nothing_to_do_errs(tmp_path: Path) -> None:
    path = _scaffold_app(tmp_path)
    result = SAFETY.safety_settings(path=path, app_name="myapp", agent_name="asst")
    assert not result["ok"] and "nothing to set" in result["error"]


def test_settings_preserves_existing_gcc(tmp_path: Path) -> None:
    """gemini_safety merges with an existing generate_content_config (temperature preserved)."""
    path = _scaffold_app(tmp_path)
    from adk_toolkit_mcp.domains.models import generate_config

    assert generate_config(path=path, app_name="myapp", agent_name="asst", temperature=0.5)["ok"]
    assert SAFETY.safety_settings(
        path=path,
        app_name="myapp",
        agent_name="asst",
        gemini_safety=[{"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_ONLY_HIGH"}],
    )["ok"]
    model = load_model(Workspace(Path(path) / "myapp"), "myapp")
    gcc = model.get("asst").generate_content_config
    assert gcc.temperature == 0.5  # preserved
    assert gcc.safety_settings[0].category == "HARM_CATEGORY_HATE_SPEECH"


# --------------------------------------------------------------------------- #
# Rendering generated by safety_plugins — ast-valid (sanity)
# --------------------------------------------------------------------------- #
def test_plugins_render_ast_valid() -> None:
    import ast

    src = safety_plugins.render_plugins_module(
        [
            {"var": "lg", "name": "lg", "kind": "logging", "denylist": []},
            {"var": "dl", "name": "dl", "kind": "tool_denylist", "denylist": ["rm"]},
        ]
    )
    ast.parse(src)


# --------------------------------------------------------------------------- #
# Read-through fastmcp.Client (exposed names + add_callback call)
# --------------------------------------------------------------------------- #
async def test_client_exposed_names_and_add_callback(tmp_path: Path) -> None:
    """Tools exposed as safety_<bare> (no double prefix); safety_add_callback via the client."""
    path = _scaffold_app(tmp_path)
    mcp = build_server()
    async with Client(mcp) as client:
        tools = await client.list_tools()
        names = {t.name for t in tools}
        assert {"safety_add_callback", "safety_add_plugin", "safety_settings"} <= names
        assert not any(n.startswith("safety_safety_") for n in names)

        called = await client.call_tool(
            "safety_add_callback",
            {
                "path": path,
                "app_name": "myapp",
                "agent_name": "asst",
                "hook": "before_model",
                "policy": {"kind": "max_input_chars", "max_chars": "1000"},
            },
        )
        payload = _client_payload(called)
        assert payload["ok"], payload.get("error")
        assert payload["data"]["callback"]["policy"] == "max_input_chars"


def _client_payload(result: Any) -> dict[str, Any]:
    """Extract the envelope dict from a fastmcp CallToolResult (structured or JSON text)."""
    data = getattr(result, "data", None)
    if isinstance(data, dict):
        return data
    structured = getattr(result, "structured_content", None)
    if isinstance(structured, dict) and "ok" in structured:
        return structured
    content = result.content[0]
    return json.loads(content.text)
